language: scala

sudo: required

dist: trusty

jdk:
  - oraclejdk8

scala:
   - 2.11.8
   - 2.12.1

cache:
  directories:
    - $HOME/.m2
    - $HOME/.sbt/0.13/dependency
    - $HOME/.sbt/boot/scala*
    - $HOME/.sbt/launchers
    - $HOME/.ivy2
    - $HOME/.nvm

env:
  global:
    - TRAVIS_NODE_VERSION="4"

before_install:
  - export PATH=${PATH}:./vendor/bundle

install:
  # http://austinpray.com/ops/2015/09/20/change-travis-node-version.html
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - rvm use 2.2.3 --install --fuzzy
  - gem update --system
  - gem install sass
  - gem install jekyll -v 3.2.1

script:
  - scripts/travis-build.sh

after_success:
  - scripts/travis-coverage.sh

branches:
  only:
    - master