language: scala

sudo: required

dist: trusty

jdk:
  - openjdk8
  - openjdk11

scala:
  - 2.11.12
  - 2.12.9
  - 2.13.0

cache:
  directories:
    - $HOME/.m2
    - $HOME/.sbt/0.13/dependency
    - $HOME/.sbt/1.0/dependency
    - $HOME/.sbt/boot/scala*
    - $HOME/.sbt/launchers
    - $HOME/.ivy2
    - $HOME/.cache/coursier/v1
    - $HOME/.nvm

env:
  global:
    - TRAVIS_NODE_VERSION="5"

addons:
  apt:
    packages:
      - graphviz

before_install:
  - export PATH=${PATH}:./vendor/bundle
  - git fetch --tags

install:
  - scripts/travis-setup.sh

script:
  - scripts/travis-build.sh

stages:
  - name: test
  - name: docs
  - name: release
    if: (branch = master AND type = push) OR (tag IS present) AND NOT fork

jobs:
  include:
    - stage: docs
      script: sbt clean makeMicrosite

    - stage: release
      script: scripts/travis-release.sh

branches:
  only:
    - master
    - /v.+/
